### Image
image:
  image: kestra/kestra
  tag: latest-full
  pullPolicy: Always

imagePullSecrets: []


### Configurations for deployments
configuration: {}


### Secrets for deployments
secrets: {}


### configuration files
configurationPath:


### Kestra executable
executable: /app/kestra


### Deployments
deployments:
  webserver:
    enabled: false
    kind: Deployment
    replicaCount: 1
    command: "server webserver"
    resources: {}
    nodeSelector: {}
    tolerations: []
    affinity: {}
    strategy: {}
    podSecurityContext: {}
    securityContext: {}
    terminationGracePeriodSeconds: 30
    extraContainers: []
    autoscaler:
      enabled: false
      minReplicas: 1
      maxReplicas: 3
      extra: {}
      metrics: []
      #  - type: Resource
      #    resource:
      #      name: cpu
      #      target:
      #        type: Utilization
      #        averageUtilization: 50
      #  - type: Resource
      #    resource:
      #      name: memory
      #      target:
      #        type: AverageValue
      #        averageValue: 100Mi

  executor:
    enabled: false
    kind: Deployment
    command: "server executor"

  indexer:
    enabled: false
    kind: Deployment
    command: "server indexer"

  scheduler:
    enabled: false
    kind: Deployment
    command: "server scheduler"

  worker:
    enabled: false
    kind: Deployment
    command: "server worker --thread={{ .Values.deployments.worker.workerThreads }}"
    terminationGracePeriodSeconds: 60
    workerThreads: 128

  standalone:
    enabled: true
    kind: Deployment
    command: "server standalone --worker-thread={{ .Values.deployments.standalone.workerThreads }}"
    terminationGracePeriodSeconds: 60
    workerThreads: 128

# EE only - Define additional group of workers.
# Must be used in addition to default workers (in standalone or separate worker deployment).
workerGroup:
  workergroupname: # name of the worker group
    enabled: false
    kind: Deployment
    command: "server worker --thread={{ .Values.workerGroup.workergroupname.workerThreads }} --worker-group={{ .WorkerGroup }}"
    terminationGracePeriodSeconds: 60
    workerThreads: 128

# for io.kestra.core.tasks.scripts.Bash task or io.kestra.plugin.scripts.*, attach a docker dind container in order to isolate in a container
# every command launch
dind:
  enabled: true
  image:
    image: docker
    tag: dind-rootless
    pullPolicy: IfNotPresent
  socketPath: /dind/
  tmpPath: /tmp/
  resources: {}
  args:
    - --log-level=fatal
    - --group=1000
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
  extraVolumeMounts: []
  extraEnv: []

### Kafka
kafka:
  enabled: false

### ElasticSearch
elasticsearch:
  enabled: false
  clusterName: "es-kestra"

  esConfig:
    elasticsearch.yml: |
      xpack:
        security:
          enabled: false

  antiAffinity: "soft"

  roles:
    ml: "false"


### Minio
minio:
  enabled: false
  #rootUser: please-change-me
  #rootPassword: its-not-a-secret
  #mode: standalone
  #persistence:
   # size: 8Gi
  #buckets:
   # - name: kestra
    #  policy: none
     # purge: false

### GCS
secrets:
  kestra:
    storage:
      type: gcs
      gcs:
        bucket: "kestra_bckt"
        service-account: |
          {
            "type": "service_account",
            "project_id": "kestra-deployment",
            "private_key_id": "ec8e5e4e1e81364b43283355a72611a98096873b",
            "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDTDhZ6cbFMrruq\nPuNN55byAt8Bt+EJTwAMPzdiRKYJGb+FA2xS9H4u2XAKNI4xSeNLTt7ubEQPPaSh\n7DYNo7GwzI9DIXuKnKzF0zIedO/MrIDrSCo3DAJfQV/MjH7E0NDaeFE4wNa8+H/u\nTS85JDF6HyLLjx9PBcPN+NgHEW5rPdUsDJSGK3KtVy1mgPW9EI8ZjuwYoDBVf9Kf\n7fOHdU5OouobjcOyjp3Lyp5Oq33C4rdfK42xZkopPlizyHAnx3nNhVctOKnjeyCU\nso3lyvvy/fox43v3VUA/ZvkR8F8OmV90mxyhED20yWNC5BNqglY79OajDWGgL1Go\nOnWiofYtAgMBAAECggEAD11QL5vFP4Lc8JjhbVN1vqqM15AuVsIki7+yZXn/6Fuy\ngJluMl/QK9LygBuxWk85t8rHGe5RyhY/vPX4PWf0UJ2jtExktQOQ5FnqpSL4LhtE\ny1wWjqlWJt8YfUihFezpt23Y49vOBjXFAnEmBe/nli9cFhuWOOd/iKgb+e+/7RiS\nafOeld4Zsh2BcN9kD47slNwIWQf4mWEw4yd3yOTwNEX1n+IZ4D487626u/zWPOku\nstJz4wFTyxJ+kIzmWOh0UrwJjRBMlIPBqSUWsIbyfs3KShH6eww2I4f3c0xLwoUr\nwPdDbwLvXUlGmxRmGutOMnoYyoKrnBsaTDBwk/PWNQKBgQDsjGXw1otdshl27WjA\naRTi1AUzetR7tXe+GNFr0Df4PYmvwNGtgOjW+ZLXxWvinrhPZ/o95NDzJEgJp386\n4LEu5IMrx4PdbqFEOmLyRfP2qitiXrQS9lqmSXvi98wpG/ZS11JpCiGjJjlloXS1\nqajGbO+Q/sPt1BsTVfkKOW0M9wKBgQDkaQaal38NZ3UcdKZngCTf2R3pfrX+fiGb\nWcB1BgYQTPi3i70efgy8XMeONf6409FbCK1GtNrxzMRtQTiUbDqNfTDxjI/0frS4\naFQ7OPG9qj/VsxVpDlssyAkU9gsmSifxuYHFjNMcZW0sPWrLoHjrF38RrcJxjjo2\nGJZ6rqvA+wKBgBvMrDZPoHVUdvWpFQR31QKLVEkmiE45l2b517LJ96nu4X2MNZgk\nbDjHf+BnzTQG3zZFy/z2JTBN9UFdM/Chc3FFXb0JZ4/gbodsLTC30+ILQan/4z3P\nQfwE6tBTuuSh6qL1tzOtAyL/XQN6pBKta65WIxlxN2l94ei109zFvvElAoGBANR7\nm6gevRQUJY8mOVNZk3Qmf7wio12vqsXhVbfHtcZeRJZDSdje/CwSx5XVRzRb4Ium\nY8O+JVwB2M2meeMhV8seJnTfBWA2qxpN++XoEIMXqTC823MS5uCe6kv0o+Sn4cbu\ngvnrCs2E0W3xaLMrgrF49z3T/mozHJYMg5h3e9IXAoGAet67Q7bSTmoSfxtgCNWe\nbap5KBRS6GQozVAT3fyXLe/CUMTIbihixjNwTo0tit12UH2peqsPFke+uJJiXheq\ngCVKGeoZboieCfd/cKGiyCjN6IK5Q+pnfmuUrt6ycOlZE4rzO5pMnj8aYOvGMyk3\nKZShm8uXJTQcLGjR+0/TVLI=\n-----END PRIVATE KEY-----\n",
            "client_email": "kestra-service@kestra-deployment.iam.gserviceaccount.com",
            "client_id": "110288454522409203064",
            "auth_uri": "https://accounts.google.com/o/oauth2/auth",
            "token_uri": "https://oauth2.googleapis.com/token",
            "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
            "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/kestra-service%40kestra-deployment.iam.gserviceaccount.com",
            "universe_domain": "googleapis.com"
          }

### Postgresql
postgresql:
  enabled: true
  auth:
    database: kestra
    username: kestra
    password: kestra

  primary:
    persistence:
      enabled: true
      size: 8Gi

### Service
service:
  type: NodePort
  port: 8080
  annotations: {}


### Ingress
ingress:
  enabled: true
  className: gce
  annotations: {}
    # kubernetes.io/ingress.class: nginx
  # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local


### Global Deployement
nameOverride: ""
serviceAccountName: ""


### Annotations for deployments
annotations: {}
podAnnotations: {}
initContainers: []

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

terminationGracePeriodSeconds: 30

nodeSelector: {}

tolerations: []

affinity: {}

extraVolumeMounts: []

extraVolumes: []

extraEnv: []

extraContainers: []

podSecurityContext: {}
# fsGroup: 2000

securityContext:
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000

### Readiness / Liveness probe config.
### ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/
readinessProbe:
  enabled: true
  path: /health
  port: management
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 3
  httpGetExtra: {}

livenessProbe:
  enabled: true
  path: /health
  port: management
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 3
  httpGetExtra: {}
