apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  annotations:
    kubernetes.io/ingress.class: "gce"
spec:
  backend:
    serviceName: {{ $fullNameService }}
    servicePort: {{ $svcPort }}
  rules:
  - http:
      paths:
      - path: /*
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ $fullNameService }}
            port:
              number: {{ $svcPort }}
  healthCheck:
    path: /health
    port: 8081